server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # 禁止访问隐藏文件
    location ~ /\. {
        deny all;
    }

    # 文本文件压缩，减少 CDN 加载时间
    gzip on;
    gzip_types text/html text/plain text/css application/javascript;
}
